
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1076872
	#The name of the modpack
	modpackName = "A Pleasant Day"
	#The version of the modpack
	modpackVersion = v0.1.3
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

