
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.tropicraft]
			mahogany = true
			palm = true
			kapok = true
			fruit = true
			grapefruit = true
			lemon = true
			lime = true
			orange = true
			papaya = true
			white_flowering = true
			red_flowering = true
			blue_flowering = true
			purple_flowering = true
			yellow_flowering = true
			red_mangrove = true
			tall_mangrove = true
			tea_mangrove = true
			black_mangrove = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.wood_type]

		[types.wood_type.tropicraft]
			mahogany = true
			palm = true
			mangrove = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			chest = true
			stripped_post = true
			ladder = true
			trapped_chest = true
			bookshelf = true
			hollow_log = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

